version: '3.9'

services:

  db:
    image: postgres:12.0-alpine
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    command: >
      sh -c "./entrypoint.sh"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:80"

volumes:
  postgres_data:
